services:
  db:
    image: postgres:16
    container_name: database-cardiologia
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: tp-cardiologia
      TZ: America/Argentina/Buenos_Aires
    ports:
      - '5432:5432'
    volumes:
      - ./schema/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
